/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  GifsApi,
  StickersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { GiphyCustom } from "./client-custom";

export class Giphy extends GiphyCustom {
  readonly gifs: GifsApi;
  readonly stickers: StickersApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.gifs = new GifsApi(configuration);
    this.stickers = new StickersApi(configuration);
  }

}
