/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GifImagesDownsized } from './gif-images-downsized';
import { GifImagesDownsizedLarge } from './gif-images-downsized-large';
import { GifImagesDownsizedMedium } from './gif-images-downsized-medium';
import { GifImagesDownsizedSmall } from './gif-images-downsized-small';
import { GifImagesDownsizedStill } from './gif-images-downsized-still';
import { GifImagesFixedHeight } from './gif-images-fixed-height';
import { GifImagesFixedHeightDownsampled } from './gif-images-fixed-height-downsampled';
import { GifImagesFixedHeightSmall } from './gif-images-fixed-height-small';
import { GifImagesFixedHeightSmallStill } from './gif-images-fixed-height-small-still';
import { GifImagesFixedHeightStill } from './gif-images-fixed-height-still';
import { GifImagesFixedWidth } from './gif-images-fixed-width';
import { GifImagesFixedWidthDownsampled } from './gif-images-fixed-width-downsampled';
import { GifImagesFixedWidthSmall } from './gif-images-fixed-width-small';
import { GifImagesFixedWidthSmallStill } from './gif-images-fixed-width-small-still';
import { GifImagesFixedWidthStill } from './gif-images-fixed-width-still';
import { GifImagesLooping } from './gif-images-looping';
import { GifImagesOriginal } from './gif-images-original';
import { GifImagesOriginalStill } from './gif-images-original-still';
import { GifImagesPreview } from './gif-images-preview';
import { GifImagesPreviewGif } from './gif-images-preview-gif';

/**
 * An object containing data for various available formats and sizes of this GIF.
 * @export
 * @interface GifImages
 */
export interface GifImages {
    /**
     * 
     * @type {GifImagesDownsized}
     * @memberof GifImages
     */
    'downsized'?: GifImagesDownsized;
    /**
     * 
     * @type {GifImagesDownsizedLarge}
     * @memberof GifImages
     */
    'downsized_large'?: GifImagesDownsizedLarge;
    /**
     * 
     * @type {GifImagesDownsizedMedium}
     * @memberof GifImages
     */
    'downsized_medium'?: GifImagesDownsizedMedium;
    /**
     * 
     * @type {GifImagesDownsizedSmall}
     * @memberof GifImages
     */
    'downsized_small'?: GifImagesDownsizedSmall;
    /**
     * 
     * @type {GifImagesDownsizedStill}
     * @memberof GifImages
     */
    'downsized_still'?: GifImagesDownsizedStill;
    /**
     * 
     * @type {GifImagesFixedHeight}
     * @memberof GifImages
     */
    'fixed_height'?: GifImagesFixedHeight;
    /**
     * 
     * @type {GifImagesFixedHeightDownsampled}
     * @memberof GifImages
     */
    'fixed_height_downsampled'?: GifImagesFixedHeightDownsampled;
    /**
     * 
     * @type {GifImagesFixedHeightSmall}
     * @memberof GifImages
     */
    'fixed_height_small'?: GifImagesFixedHeightSmall;
    /**
     * 
     * @type {GifImagesFixedHeightSmallStill}
     * @memberof GifImages
     */
    'fixed_height_small_still'?: GifImagesFixedHeightSmallStill;
    /**
     * 
     * @type {GifImagesFixedHeightStill}
     * @memberof GifImages
     */
    'fixed_height_still'?: GifImagesFixedHeightStill;
    /**
     * 
     * @type {GifImagesFixedWidth}
     * @memberof GifImages
     */
    'fixed_width'?: GifImagesFixedWidth;
    /**
     * 
     * @type {GifImagesFixedWidthDownsampled}
     * @memberof GifImages
     */
    'fixed_width_downsampled'?: GifImagesFixedWidthDownsampled;
    /**
     * 
     * @type {GifImagesFixedWidthSmall}
     * @memberof GifImages
     */
    'fixed_width_small'?: GifImagesFixedWidthSmall;
    /**
     * 
     * @type {GifImagesFixedWidthSmallStill}
     * @memberof GifImages
     */
    'fixed_width_small_still'?: GifImagesFixedWidthSmallStill;
    /**
     * 
     * @type {GifImagesFixedWidthStill}
     * @memberof GifImages
     */
    'fixed_width_still'?: GifImagesFixedWidthStill;
    /**
     * 
     * @type {GifImagesLooping}
     * @memberof GifImages
     */
    'looping'?: GifImagesLooping;
    /**
     * 
     * @type {GifImagesOriginal}
     * @memberof GifImages
     */
    'original'?: GifImagesOriginal;
    /**
     * 
     * @type {GifImagesOriginalStill}
     * @memberof GifImages
     */
    'original_still'?: GifImagesOriginalStill;
    /**
     * 
     * @type {GifImagesPreview}
     * @memberof GifImages
     */
    'preview'?: GifImagesPreview;
    /**
     * 
     * @type {GifImagesPreviewGif}
     * @memberof GifImages
     */
    'preview_gif'?: GifImagesPreviewGif;
}

