/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Gif } from './gif';
import { Meta } from './meta';
import { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface GifsSearchGifsResponse
 */
export interface GifsSearchGifsResponse {
    /**
     * 
     * @type {Array<Gif>}
     * @memberof GifsSearchGifsResponse
     */
    'data'?: Array<Gif>;
    /**
     * 
     * @type {Meta}
     * @memberof GifsSearchGifsResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Pagination}
     * @memberof GifsSearchGifsResponse
     */
    'pagination'?: Pagination;
}

