/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Gif } from './gif';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface GifsGetRandomGifResponse
 */
export interface GifsGetRandomGifResponse {
    /**
     * 
     * @type {Gif}
     * @memberof GifsGetRandomGifResponse
     */
    'data'?: Gif;
    /**
     * 
     * @type {Meta}
     * @memberof GifsGetRandomGifResponse
     */
    'meta'?: Meta;
}

