/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * The number of frames in this GIF.
     * @type {string}
     * @memberof Image
     */
    'frames'?: string;
    /**
     * The height of this GIF in pixels.
     * @type {string}
     * @memberof Image
     */
    'height'?: string;
    /**
     * The URL for this GIF in .MP4 format.
     * @type {string}
     * @memberof Image
     */
    'mp4'?: string;
    /**
     * The size in bytes of the .MP4 file corresponding to this GIF.
     * @type {string}
     * @memberof Image
     */
    'mp4_size'?: string;
    /**
     * The size of this GIF in bytes.
     * @type {string}
     * @memberof Image
     */
    'size'?: string;
    /**
     * The publicly-accessible direct URL for this GIF.
     * @type {string}
     * @memberof Image
     */
    'url'?: string;
    /**
     * The URL for this GIF in .webp format.
     * @type {string}
     * @memberof Image
     */
    'webp'?: string;
    /**
     * The size in bytes of the .webp file corresponding to this GIF.
     * @type {string}
     * @memberof Image
     */
    'webp_size'?: string;
    /**
     * The width of this GIF in pixels.
     * @type {string}
     * @memberof Image
     */
    'width'?: string;
}

