/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Meta Object contains basic information regarding the request, whether it was successful, and the response given by the API.  Check `responses` to see a description of types of response codes the API might give you under different cirumstances. 
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * HTTP Response Message
     * @type {string}
     * @memberof Meta
     */
    'msg'?: string;
    /**
     * A unique ID paired with this response from the API.
     * @type {string}
     * @memberof Meta
     */
    'response_id'?: string;
    /**
     * HTTP Response Code
     * @type {number}
     * @memberof Meta
     */
    'status'?: number;
}

