/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Pagination Object contains information relating to the number of total results available as well as the number of results fetched and their relative positions. 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * Total number of items returned.
     * @type {number}
     * @memberof Pagination
     */
    'count'?: number;
    /**
     * Position in pagination.
     * @type {number}
     * @memberof Pagination
     */
    'offset'?: number;
    /**
     * Total number of items available.
     * @type {number}
     * @memberof Pagination
     */
    'total_count'?: number;
}

