/*
Giphy API

Giphy API

The version of the OpenAPI document: 1.0
Contact: support@giphy.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The User Object contains information about the user associated with a GIF and URLs to assets such as that user\'s avatar image, profile, and more.
 * @export
 * @interface User
 */
export interface User {
    /**
     * The URL for this user\'s avatar image.
     * @type {string}
     * @memberof User
     */
    'avatar_url'?: string;
    /**
     * The URL for the banner image that appears atop this user\'s profile page.
     * @type {string}
     * @memberof User
     */
    'banner_url'?: string;
    /**
     * The display name associated with this user (contains formatting the base username might not).
     * @type {string}
     * @memberof User
     */
    'display_name'?: string;
    /**
     * The URL for this user\'s profile.
     * @type {string}
     * @memberof User
     */
    'profile_url'?: string;
    /**
     * The Twitter username associated with this user, if applicable.
     * @type {string}
     * @memberof User
     */
    'twitter'?: string;
    /**
     * The username associated with this user.
     * @type {string}
     * @memberof User
     */
    'username'?: string;
}

